package com.jn.sqlhelper.examples.common.model;

import java.util.Date;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.ID
     *
     * @mbg.generated Sun Jun 07 18:01:39 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.NAME
     *
     * @mbg.generated Sun Jun 07 18:01:39 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.ADDRESS
     *
     * @mbg.generated Sun Jun 07 18:01:39 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.CITY
     *
     * @mbg.generated Sun Jun 07 18:01:39 CST 2020
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.COUNTRY
     *
     * @mbg.generated Sun Jun 07 18:01:39 CST 2020
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.BIRTHDATE
     *
     * @mbg.generated Sun Jun 07 18:01:39 CST 2020
     */
    private Date birthdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.UPDATEDATE
     *
     * @mbg.generated Sun Jun 07 18:01:39 CST 2020
     */
    private Date updatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.ID
     *
     * @return the value of CUSTOMER.ID
     *
     * @mbg.generated Sun Jun 07 18:01:39 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.ID
     *
     * @param id the value for CUSTOMER.ID
     *
     * @mbg.generated Sun Jun 07 18:01:39 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.NAME
     *
     * @return the value of CUSTOMER.NAME
     *
     * @mbg.generated Sun Jun 07 18:01:39 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.NAME
     *
     * @param name the value for CUSTOMER.NAME
     *
     * @mbg.generated Sun Jun 07 18:01:39 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.ADDRESS
     *
     * @return the value of CUSTOMER.ADDRESS
     *
     * @mbg.generated Sun Jun 07 18:01:39 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.ADDRESS
     *
     * @param address the value for CUSTOMER.ADDRESS
     *
     * @mbg.generated Sun Jun 07 18:01:39 CST 2020
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.CITY
     *
     * @return the value of CUSTOMER.CITY
     *
     * @mbg.generated Sun Jun 07 18:01:39 CST 2020
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.CITY
     *
     * @param city the value for CUSTOMER.CITY
     *
     * @mbg.generated Sun Jun 07 18:01:39 CST 2020
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.COUNTRY
     *
     * @return the value of CUSTOMER.COUNTRY
     *
     * @mbg.generated Sun Jun 07 18:01:39 CST 2020
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.COUNTRY
     *
     * @param country the value for CUSTOMER.COUNTRY
     *
     * @mbg.generated Sun Jun 07 18:01:39 CST 2020
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.BIRTHDATE
     *
     * @return the value of CUSTOMER.BIRTHDATE
     *
     * @mbg.generated Sun Jun 07 18:01:39 CST 2020
     */
    public Date getBirthdate() {
        return birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.BIRTHDATE
     *
     * @param birthdate the value for CUSTOMER.BIRTHDATE
     *
     * @mbg.generated Sun Jun 07 18:01:39 CST 2020
     */
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.UPDATEDATE
     *
     * @return the value of CUSTOMER.UPDATEDATE
     *
     * @mbg.generated Sun Jun 07 18:01:39 CST 2020
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.UPDATEDATE
     *
     * @param updatedate the value for CUSTOMER.UPDATEDATE
     *
     * @mbg.generated Sun Jun 07 18:01:39 CST 2020
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }
}