server:
  port: 8087

spring:
  datasource:
    url: jdbc:h2:file:${user.dir}/sqlhelper-examples/sqlhelper-examples-db/src/main/resources/test
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456
    name: slave3
  h2:
    console:
      enabled: true
  jpa:
    database: default
    hibernate:
      ddl-auto: none

sqlhelper:
  dynamic-datasource:
    enabled: true

swagger:
  base-package: com.jn.sqlhelper.examples.hibernate.controller
  application-title: SQLHelper + JPA + Hibernate

logging:
  level:
    root: info
    com:
      jn:
        sqlhelper:
          examples:
            common:
              dao: trace
          mybatis:
            plugins:
              likeescape: debug
            spring:
              session:
                factory:
                  dynamicdatasource:
                    DynamicDataSourceManagedTransaction: debug
          datasource:
            key:
              DataSourceKeySelector: debug
