server:
  port: 8084

spring:
  #datasource:
  #  url: jdbc:h2:file:${user.dir}/sqlhelper-examples/sqlhelper-examples-db/src/main/resources/test
  #  driver-class-name: org.h2.Driver
  #  username: sa
  #  password: DZ3DPr9XZT9jj4S8S09GOBdPK1Cwd7TaU9BXbxItaXHq6A8yDnaCuHMaAydTAVN6zPiA3nHFFpJ2H0ETeqcf5Q==
  #  name: slave3
  h2:
    console:
      enabled: true
  jpa:
    database: default

swagger:
  base-package: com.jn.sqlhelper.examples.mybatis.controller
  application-title: SQLHelper + JPA + Hibernate

logging:
  level:
    root: info
    com:
      jn:
        sqlhelper:
          examples:
            common:
              dao: trace
          mybatis:
            plugins:
              likeescape: debug
            spring:
              session:
                factory:
                  dynamicdatasource:
                    DynamicDataSourceManagedTransaction: debug
          datasource:
            key:
              DataSourceKeySelector: debug
