server:
  port: 8087

mybatis:
  type-aliases-package: com.jn.sqlhelper.examples.model
  mapper-locations: classpath*:mapper/*.xml

spring:
  # https://h2database.com/
  datasource:
    url: jdbc:h2:file:${user.dir}/sqlhelper-examples/sqlhelper-examples-db/src/main/resources/test
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456

swagger:
  base-package: com.jn.sqlhelper.examples.mybatisplus3.controller
  application-title: SQLHelper + MyBatis

mybatis-plus:
  type-aliases-package: com.jn.sqlhelper.examples.model
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-column-underline: true
    jdbc-type-for-null: 'null'

logging:
  level:
    root: info
    com:
      jn:
        sqlhelper:
          examples:
            common:
              dao: trace
          mybatis:
            plugins:
              likeescape: debug

sqlhelper:
  dynamicDataSource:
    enabled: true
    key-choices-pointcut:
      expression: execution(public * com.jn.sqlhelper.examples.mybatisplus3.controller.*Controller.*(..))
    dataSources:
      # https://h2database.com/
      - group: primary
        name: master
        url: jdbc:h2:file:${user.dir}/sqlhelper-examples/sqlhelper-examples-db/src/main/resources/test
        driver-class-name: org.h2.Driver
        username: sa
        password: 123456
      - group: primary
        name: slave1
        url: jdbc:h2:file:${user.dir}/sqlhelper-examples/sqlhelper-examples-db/src/main/resources/test
        driver-class-name: org.h2.Driver
        username: sa
        password: 123456
      - group: primary
        name: slave2
        url: jdbc:h2:file:${user.dir}/sqlhelper-examples/sqlhelper-examples-db/src/main/resources/test
        driver-class-name: org.h2.Driver
        username: sa
        password: 123456
operation:
  definition:
    location: classpath:/operation.yml
    reload-interval-in-seconds: 0
audit:
  enabled: true
  debug-consumer-enabled: true
  topics:
    - DEFAULT
  topic-configs:
    - name: DEFAULT
      ring-buffer-size: 1024
      producer-type: SINGLE
  http-interceptor-patterns:
    - /consumers/**
    - /users/**
  advisor-pointcut:
    expression: execution(public * com.jn.sqlhelper.examples.mybatisplus3.controller.*Controller.*(..))